// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: quicClient/model.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Line struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocId          string `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	DocVersion     int64  `protobuf:"varint,2,opt,name=doc_version,json=docVersion,proto3" json:"doc_version,omitempty"`
	DocSeqNo       int64  `protobuf:"varint,3,opt,name=doc_seq_no,json=docSeqNo,proto3" json:"doc_seq_no,omitempty"`
	DocPrimaryTerm int64  `protobuf:"varint,4,opt,name=doc_primary_term,json=docPrimaryTerm,proto3" json:"doc_primary_term,omitempty"`
	Source         string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	SourceIsCore   bool   `protobuf:"varint,6,opt,name=source_is_core,json=sourceIsCore,proto3" json:"source_is_core,omitempty"`
	SourceScene    string `protobuf:"bytes,7,opt,name=source_scene,json=sourceScene,proto3" json:"source_scene,omitempty"`
	Target         string `protobuf:"bytes,8,opt,name=target,proto3" json:"target,omitempty"`
	TargetIsCore   bool   `protobuf:"varint,9,opt,name=target_is_core,json=targetIsCore,proto3" json:"target_is_core,omitempty"`
	TargetScene    string `protobuf:"bytes,10,opt,name=target_scene,json=targetScene,proto3" json:"target_scene,omitempty"`
	Dependence     string `protobuf:"bytes,11,opt,name=dependence,proto3" json:"dependence,omitempty"`
	VisitCount     int64  `protobuf:"varint,12,opt,name=visit_count,json=visitCount,proto3" json:"visit_count,omitempty"`
}

func (x *Line) Reset() {
	*x = Line{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quicClient_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_quicClient_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Line.ProtoReflect.Descriptor instead.
func (*Line) Descriptor() ([]byte, []int) {
	return file_quicClient_model_proto_rawDescGZIP(), []int{0}
}

func (x *Line) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *Line) GetDocVersion() int64 {
	if x != nil {
		return x.DocVersion
	}
	return 0
}

func (x *Line) GetDocSeqNo() int64 {
	if x != nil {
		return x.DocSeqNo
	}
	return 0
}

func (x *Line) GetDocPrimaryTerm() int64 {
	if x != nil {
		return x.DocPrimaryTerm
	}
	return 0
}

func (x *Line) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Line) GetSourceIsCore() bool {
	if x != nil {
		return x.SourceIsCore
	}
	return false
}

func (x *Line) GetSourceScene() string {
	if x != nil {
		return x.SourceScene
	}
	return ""
}

func (x *Line) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Line) GetTargetIsCore() bool {
	if x != nil {
		return x.TargetIsCore
	}
	return false
}

func (x *Line) GetTargetScene() string {
	if x != nil {
		return x.TargetScene
	}
	return ""
}

func (x *Line) GetDependence() string {
	if x != nil {
		return x.Dependence
	}
	return ""
}

func (x *Line) GetVisitCount() int64 {
	if x != nil {
		return x.VisitCount
	}
	return 0
}

type LineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nums  int64     `protobuf:"varint,1,opt,name=nums,proto3" json:"nums,omitempty"`
	Lines *LineList `protobuf:"bytes,2,opt,name=lines,proto3" json:"lines,omitempty"`
}

func (x *LineReq) Reset() {
	*x = LineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quicClient_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineReq) ProtoMessage() {}

func (x *LineReq) ProtoReflect() protoreflect.Message {
	mi := &file_quicClient_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineReq.ProtoReflect.Descriptor instead.
func (*LineReq) Descriptor() ([]byte, []int) {
	return file_quicClient_model_proto_rawDescGZIP(), []int{1}
}

func (x *LineReq) GetNums() int64 {
	if x != nil {
		return x.Nums
	}
	return 0
}

func (x *LineReq) GetLines() *LineList {
	if x != nil {
		return x.Lines
	}
	return nil
}

type LineResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *LineResp) Reset() {
	*x = LineResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quicClient_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineResp) ProtoMessage() {}

func (x *LineResp) ProtoReflect() protoreflect.Message {
	mi := &file_quicClient_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineResp.ProtoReflect.Descriptor instead.
func (*LineResp) Descriptor() ([]byte, []int) {
	return file_quicClient_model_proto_rawDescGZIP(), []int{2}
}

func (x *LineResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type LineList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*Line `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *LineList) Reset() {
	*x = LineList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quicClient_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineList) ProtoMessage() {}

func (x *LineList) ProtoReflect() protoreflect.Message {
	mi := &file_quicClient_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineList.ProtoReflect.Descriptor instead.
func (*LineList) Descriptor() ([]byte, []int) {
	return file_quicClient_model_proto_rawDescGZIP(), []int{3}
}

func (x *LineList) GetMessages() []*Line {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ErrorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ErrorResp) Reset() {
	*x = ErrorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quicClient_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResp) ProtoMessage() {}

func (x *ErrorResp) ProtoReflect() protoreflect.Message {
	mi := &file_quicClient_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResp.ProtoReflect.Descriptor instead.
func (*ErrorResp) Descriptor() ([]byte, []int) {
	return file_quicClient_model_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_quicClient_model_proto protoreflect.FileDescriptor

var file_quicClient_model_proto_rawDesc = []byte{
	0x0a, 0x16, 0x71, 0x75, 0x69, 0x63, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x03, 0x0a, 0x04, 0x4c, 0x69, 0x6e,
	0x65, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x64, 0x6f, 0x63, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64,
	0x6f, 0x63, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x0a, 0x64, 0x6f, 0x63,
	0x5f, 0x73, 0x65, 0x71, 0x5f, 0x6e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64,
	0x6f, 0x63, 0x53, 0x65, 0x71, 0x4e, 0x6f, 0x12, 0x28, 0x0a, 0x10, 0x64, 0x6f, 0x63, 0x5f, 0x70,
	0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0e, 0x64, 0x6f, 0x63, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x54, 0x65, 0x72,
	0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x5f, 0x69, 0x73, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x73, 0x43, 0x6f, 0x72, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x73, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x73, 0x43, 0x6f, 0x72, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x73, 0x63, 0x65, 0x6e, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x63,
	0x65, 0x6e, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x69, 0x73, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x74, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3e, 0x0a, 0x07, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6e,
	0x75, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x6c,
	0x69, 0x6e, 0x65, 0x73, 0x22, 0x1c, 0x0a, 0x08, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x2d, 0x0a, 0x08, 0x4c, 0x69, 0x6e, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21,
	0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x22, 0x39, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x12, 0x5a, 0x10,
	0x71, 0x75, 0x69, 0x63, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quicClient_model_proto_rawDescOnce sync.Once
	file_quicClient_model_proto_rawDescData = file_quicClient_model_proto_rawDesc
)

func file_quicClient_model_proto_rawDescGZIP() []byte {
	file_quicClient_model_proto_rawDescOnce.Do(func() {
		file_quicClient_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_quicClient_model_proto_rawDescData)
	})
	return file_quicClient_model_proto_rawDescData
}

var file_quicClient_model_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_quicClient_model_proto_goTypes = []interface{}{
	(*Line)(nil),      // 0: Line
	(*LineReq)(nil),   // 1: LineReq
	(*LineResp)(nil),  // 2: LineResp
	(*LineList)(nil),  // 3: LineList
	(*ErrorResp)(nil), // 4: ErrorResp
}
var file_quicClient_model_proto_depIdxs = []int32{
	3, // 0: LineReq.lines:type_name -> LineList
	0, // 1: LineList.messages:type_name -> Line
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_quicClient_model_proto_init() }
func file_quicClient_model_proto_init() {
	if File_quicClient_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quicClient_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Line); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quicClient_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quicClient_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quicClient_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quicClient_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quicClient_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quicClient_model_proto_goTypes,
		DependencyIndexes: file_quicClient_model_proto_depIdxs,
		MessageInfos:      file_quicClient_model_proto_msgTypes,
	}.Build()
	File_quicClient_model_proto = out.File
	file_quicClient_model_proto_rawDesc = nil
	file_quicClient_model_proto_goTypes = nil
	file_quicClient_model_proto_depIdxs = nil
}
